/* =====================================================================
   RE:ZERO — fiches encyclopédiques des personnages (FR, vérifié)
   img = assets/img/<id>.webp
   ===================================================================== */
RZ.groups = [
  {id:"principaux", label:"Personnages principaux"},
  {id:"roswaal",    label:"Domaine Roswaal"},
  {id:"royale",     label:"La Sélection Royale"},
  {id:"chevaliers", label:"Les Chevaliers"},
  {id:"sorcieres",  label:"Sorcières & Culte des Sorcières"},
  {id:"vollachia",  label:"L'Empire de Vollachia"},
  {id:"autres",     label:"Autres figures notables"},
];

RZ.characters = [
/* ===== PRINCIPAUX ===== */
{
  id:"subaru", name:"Natsuki Subaru", kanji:"ナツキ・スバル", group:"principaux",
  color:"#e02438", role:"Protagoniste", race:"Humain", age:"≈ 17 ans",
  aff:"Camp Emilia", status:"Vivant", va:"Yūsuke Kobayashi",
  abilities:["Return by Death","Cor Leonis","Invisible Providence (empruntée)"],
  epi:"Le garçon venu d'un autre monde",
  quote:"Je t'aime, du fond du cœur, Emilia.",
  lead:"Natsuki Subaru est le protagoniste de Re:Zero. Lycéen reclus et sans avenir de notre monde, il est brutalement transporté dans le royaume de Lugnica, où il découvre qu'il ne possède ni magie, ni force, ni talent particulier — seulement un pouvoir aussi précieux que terrible : le <strong>Return by Death</strong>.",
  sections:[
    {h:"Personnalité", html:"De prime abord vantard, lâche et maladroit, Subaru cache une volonté hors du commun et une empathie sans limite. Loin du héros tout-puissant attendu d'un isekai, il pleure, panique, échoue et s'effondre — puis se relève à chaque fois. Sa plus grande force n'est pas un don, mais un cœur qui refuse de laisser mourir ceux qu'il aime, quitte à revivre l'horreur sans fin."},
    {h:"Le Return by Death", html:"À sa mort, le temps de Subaru recule jusqu'à un « point de sauvegarde » antérieur, en lui laissant l'intégralité de ses souvenirs. Ce pouvoir n'est pas un don mais une malédiction : il porte seul le poids de morts que nul ne se rappelle, et tenter d'en parler fait surgir l'ombre de la Sorcière de l'Envie, qui lui broie le cœur. Il transforme néanmoins l'enfer en stratégie, faisant de chaque échec une leçon."},
    {h:"Évolution & pouvoirs", html:"Sans capacité de combat propre, Subaru gagne par ses liens : il scelle un pacte avec l'esprit <em>Beatrice</em> (magie Yin) et développe le <em>Cor Leonis</em>, une autorité née de ses attaches qui lui permet de ressentir et de soutenir ses alliés. Arc après arc, le gamin terrifié devient un meneur dont la détermination galvanise des camps entiers."},
    {h:"Apparence", html:"Subaru a des cheveux noirs en bataille et un regard perçant, souvent qualifié de « mauvais » ou d'intimidant malgré son tempérament amical. Il conserve longtemps le survêtement orange qu'il portait au moment de son transfert, avant d'adopter des tenues plus adaptées au monde de Lugnica. Son corps, celui d'un adolescent sédentaire, est l'une de ses faiblesses constantes face aux dangers surnaturels."},
    {h:"Relations clés", html:"<strong>Emilia</strong> — la personne pour laquelle il se bat, source de sa promesse de devenir « quelqu'un de bien ». <strong>Rem</strong> — qui lui voue un amour inconditionnel et le soutient dans ses pires moments. <strong>Beatrice</strong> — son esprit contractuel, qu'il tire de quatre siècles de solitude. <strong>Otto & Garfiel</strong> — ses plus proches compagnons masculins. <strong>Satella</strong>, la Sorcière de l'Envie, entretient avec lui un lien aussi obscur que central."},
    {h:"Le poids du secret", html:"L'impossibilité de parler du Return by Death est le cœur de son drame : chaque tentative provoque l'intrusion de l'« ombre » de la Sorcière, qui lui écrase le cœur, voire tue son interlocuteur. Subaru porte donc seul le souvenir de dizaines de morts atroces, un fardeau psychologique qui le pousse plusieurs fois au bord de l'effondrement — thème central du célèbre épisode 15 de l'anime."},
  ],
  related:["emilia","rem","beatrice","satella","otto"],
},
{
  id:"emilia", name:"Emilia", kanji:"エミリア", group:"principaux",
  color:"#7fd8ff", role:"Héroïne · Candidate au trône", race:"Demi-elfe", age:"≈ 112 ans (apparence d'adolescente)",
  aff:"Camp Emilia", status:"Vivante", va:"Rie Takahashi",
  abilities:["Magie de glace (Eau)","Magie Yin","Pacte avec le Grand Esprit Puck"],
  epi:"La demi-elfe aux cheveux d'argent",
  quote:"Merci, Subaru. Cette fois… c'est moi qui te sauverai.",
  lead:"Emilia est l'héroïne de Re:Zero et l'une des cinq candidates à la succession royale de Lugnica. Demi-elfe aux cheveux d'argent et aux yeux violets, son apparence rappelle celle de la Sorcière de l'Envie, ce qui lui vaut la défiance, voire la haine, d'une grande partie du royaume.",
  sections:[
    {h:"Personnalité", html:"Profondément gentille, droite et déterminée, Emilia tend à tout porter sur ses épaules et peine à demander de l'aide. Sa naïveté apparente masque un passé traumatique et une volonté de fer : elle veut devenir reine pour bâtir un monde où nul ne serait jugé sur ses origines."},
    {h:"Histoire & magie", html:"Élevée dans la forêt gelée d'Elior, liée au Grand Esprit <em>Puck</em>, Emilia maîtrise une puissante magie de glace. Son passé, enfoui sous la glace et la mémoire, est au cœur de l'arc du Sanctuaire (arc 4), où elle affronte enfin ses souvenirs pour mûrir et accepter le soutien de Subaru."},
    {h:"Apparence", html:"Emilia possède de longs cheveux argentés, de grands yeux violet-améthyste et des oreilles pointues trahissant son ascendance elfique. Sa ressemblance frappante avec la Sorcière de l'Envie lui vaut méfiance et rejet dans tout le royaume — un préjugé qu'elle affronte avec une dignité constante."},
    {h:"Parcours", html:"Candidate improbable et discriminée, Emilia doit surmonter à la fois l'hostilité du royaume et ses propres blessures. L'arc 4 révèle la tragédie de son enfance à Elior — le village figé dans la glace, la Sorcière de la Vanité Pandora et la perte de sa mère adoptive Fortuna. En brisant le sceau de ses souvenirs, elle passe du statut d'héroïne protégée à celui d'actrice de son propre destin."},
    {h:"Relations clés", html:"<strong>Puck</strong> — son esprit et figure paternelle, dont le pacte la protège. <strong>Subaru</strong> — le premier à croire en elle sans arrière-pensée, dont l'amour la pousse à grandir. <strong>Beatrice, Rem et Ram</strong> — ses proches au sein du camp qui porte son nom. <strong>Roswaal</strong> — son sponsor politique aux motivations troubles."},
  ],
  related:["puck","subaru","satella","beatrice"],
},
{
  id:"rem", name:"Rem", kanji:"レム", group:"principaux",
  color:"#5b8eff", role:"Servante du manoir", race:"Oni (démon)", age:"Adolescente",
  aff:"Camp Emilia", status:"Vivante", va:"Inori Minase",
  abilities:["Masse à chaîne (morgenstern)","Magie de l'Eau","Forme oni (corne)"],
  epi:"La servante démone au cœur dévoué",
  quote:"Recommençons. Non pas depuis zéro… mais depuis le négatif.",
  lead:"Rem est, avec sa sœur jumelle Ram, servante au manoir Roswaal. Membre du clan des Oni, elle dissimule derrière sa douceur polie un complexe d'infériorité tenace vis-à-vis de sa sœur, qu'elle juge plus douée qu'elle.",
  sections:[
    {h:"Personnalité & rôle", html:"Méthodique et combative, Rem se hait longtemps elle-même, persuadée de ne valoir que par comparaison à Ram. Tout bascule lorsque Subaru la sauve d'elle-même : elle lui voue dès lors un amour absolu et inconditionnel, devenant son plus fervent soutien. Son discours « depuis le négatif » est l'un des sommets émotionnels de la série."},
    {h:"Destin", html:"Aux arcs ultérieurs, le nom et les souvenirs de Rem sont dévorés par l'Archevêque de la Gourmandise, la plongeant dans un profond sommeil. Sa réapparition, amnésique mais vivante, dans l'Empire de Vollachia, relance tout un pan du récit."},
    {h:"Apparence", html:"Rem a de courts cheveux bleu ciel qui masquent son œil droit, des yeux assortis et l'uniforme de servante du manoir Roswaal. Sous sa forme d'Oni, une corne blanche jaillit de son front et son mana s'emballe, décuplant sa force au prix de sa raison."},
    {h:"Relations clés", html:"<strong>Ram</strong> — sa sœur jumelle qu'elle admire jusqu'à s'effacer. <strong>Subaru</strong> — l'homme qui l'a sauvée de sa haine de soi et qu'elle aime sans condition. Son arc personnel — de la culpabilité écrasante à l'affirmation de soi — en fait l'un des personnages les plus aimés de la franchise."},
  ],
  related:["ram","subaru","roswaal"],
},
{
  id:"ram", name:"Ram", kanji:"ラム", group:"principaux",
  color:"#ff7ea8", role:"Servante du manoir", race:"Oni (démon)", age:"Adolescente",
  aff:"Camp Emilia", status:"Vivante", va:"Rie Murakawa",
  abilities:["Magie du Vent","Clairvoyance (synesthésie)","Esprit acéré"],
  epi:"La sœur aînée à la langue acérée",
  quote:"Barusu. Ne te surestime pas.",
  lead:"Ram est la sœur aînée des jumelles Oni au service de Roswaal. Hautaine, sarcastique et d'une loyauté indéfectible envers son maître, elle a perdu sa corne — et donc l'essentiel de sa puissance — lors de la destruction de son village.",
  sections:[
    {h:"Apparence", html:"Ram a de courts cheveux rose pâle, des yeux rouges et porte l'uniforme de servante du manoir. Contrairement à sa sœur, elle dégage son front, laissant deviner la marque de sa corne brisée."},
    {h:"Personnalité", html:"Fière, cinglante et d'un flegme imperturbable, Ram traite Subaru avec un mépris affectueux — elle l'affuble du surnom « Barusu » — et affiche une confiance en elle inébranlable. Derrière cette arrogance se cachent un amour protecteur immense pour sa sœur Rem et une dévotion absolue, teintée de sentiments amoureux, envers son maître Roswaal."},
    {h:"Biographie", html:"Née dans un village du clan des Oni, Ram était une prodige dotée d'une puissance colossale, symbolisée par sa corne. Lorsque le Culte des Sorcières massacra le village, sa corne fut tranchée, la privant de l'essentiel de son mana et manquant de la tuer. Roswaal recueillit les jumelles orphelines ; depuis, Ram le sert avec une loyauté sans faille et une gratitude inébranlable."},
    {h:"Pouvoirs & capacités", html:"Même diminuée, Ram demeure redoutable : elle manie la magie du vent (<em>Fula</em>, <em>Al Fula</em>) et possède une « clairvoyance » qui lui tient lieu de perception étendue, compensant sa vue affaiblie. Dans les situations extrêmes, la repousse temporaire de sa corne lui rend une fraction de sa puissance d'antan — un pouvoir dévastateur mais qui menace sa vie."},
    {h:"Relations clés", html:"<strong>Rem</strong> — sa sœur jumelle cadette, qu'elle chérit sous une carapace de froideur. <strong>Roswaal</strong> — son maître, pour qui sa dévotion dépasse le simple service. <strong>Garfiel</strong> — avec qui elle noue une relation dans les arcs ultérieurs."},
  ],
  related:["rem","roswaal","garfiel"],
},
{
  id:"beatrice", name:"Beatrice", kanji:"ベアトリス", group:"principaux",
  color:"#e7c873", role:"Esprit · Bibliothèque interdite", race:"Esprit artificiel", age:"≈ 400 ans",
  aff:"Camp Emilia", status:"Vivante", va:"Satomi Arai",
  abilities:["Magie Yin (El Minya)","La Bibliothèque interdite (Forbidden Library)"],
  epi:"L'esprit de la Bibliothèque interdite",
  quote:"Betty attendait… ce contractant, je suppose.",
  lead:"Beatrice est un esprit artificiel créé par la Sorcière de l'Avarice Echidna, gardien de la Bibliothèque interdite du manoir Roswaal. Sous les traits d'une fillette en robe à fanfreluches, elle a attendu pendant quatre siècles « celui » qu'elle devait servir.",
  sections:[
    {h:"Personnalité & lien avec Subaru", html:"Acariâtre et solitaire, Beatrice est rongée par une instruction laissée par sa créatrice : attendre indéfiniment un mystérieux contractant. Cette attente la consume jusqu'à ce que Subaru lui offre l'ordre qu'elle espérait — « Je te choisis. » Le pacte qui les unit (la magie partagée nommée <em>Echo</em>) la sauve de son désespoir et fait d'elle son arme magique la plus fidèle."},
    {h:"Apparence & tic de langage", html:"Beatrice a l'apparence d'une fillette aux longs cheveux blonds coiffés en anglaises et à la robe rose à volants. Elle parle d'elle à la troisième personne (« Betty ») et termine fréquemment ses phrases par « … kashira » (« … je suppose »), un tic caractéristique. La Bibliothèque interdite qu'elle garde peut relier des portes à travers l'espace."},
    {h:"Pouvoir", html:"En tant qu'esprit artificiel de la magie Yin, Beatrice manie <em>El Minya</em> et des sorts de manipulation de l'espace parmi les plus puissants du récit. Une fois liée à Subaru, elle devient sa principale capacité offensive et défensive, complétant sa faiblesse au combat."},
  ],
  related:["subaru","echidna","roswaal"],
},
{
  id:"puck", name:"Puck", kanji:"パック", group:"principaux",
  color:"#bdecff", role:"Grand Esprit", race:"Grand Esprit (chat)", age:"Inconnu",
  aff:"Camp Emilia", status:"Esprit", va:"Yumi Uchiyama",
  abilities:["Magie de Feu","Gel absolu","« Bête de la fin du monde »"],
  epi:"Le Grand Esprit, Bête de fin du monde",
  quote:"Je t'avais prévenu : ne fais jamais pleurer Lia.",
  lead:"Puck est le Grand Esprit lié par contrat à Emilia, apparaissant le plus souvent sous la forme d'un petit chat gris adorable. Derrière cette apparence inoffensive se cache l'une des entités les plus puissantes du récit, surnommée la « Bête de la fin du monde ».",
  sections:[
    {h:"Apparence", html:"Puck se manifeste sous la forme d'un petit chat gris à la queue rayée, tenant dans une paume — mignon et débonnaire. Cette forme n'est qu'une fraction de sa véritable puissance : en tant que « Bête de la fin du monde », il peut adopter une forme colossale capable de geler des régions entières."},
    {h:"Personnalité", html:"Espiègle, taquin et profondément affectueux, Puck joue le rôle d'un père pour Emilia et de mentor pour Subaru. Derrière son humour se cache toutefois un pragmatisme glaçant : pour lui, la survie et le bonheur d'Emilia priment sur le reste du monde, sans la moindre hésitation."},
    {h:"Pacte & pouvoirs", html:"Grand Esprit de l'attribut du feu, Puck manie paradoxalement un froid absolu dévastateur. Il n'est actif que durant la journée et puise son énergie dans le cristal-pierre que porte Emilia, cœur de leur contrat. Ses conditions sont strictes — et l'une d'elles est sans appel : si Emilia venait à mourir, il briserait le pacte et gèlerait le monde entier."},
    {h:"Origines", html:"La nature exacte de Puck est l'un des mystères de l'œuvre : son existence est liée à la Sorcière de l'Avarice <em>Echidna</em>, ce qui le rapproche des esprits artificiels comme Beatrice. Son passé et son lien avec Emilia sont explorés dans l'OAV <em>Le Lien de Glace</em>."},
  ],
  related:["emilia","beatrice","echidna"],
},
/* ===== DOMAINE ROSWAAL ===== */
{
  id:"roswaal", name:"Roswaal L. Mathers", kanji:"ロズワール・L・メイザース", group:"roswaal",
  color:"#a06bff", role:"Margrave · Mage de cour", race:"Humain", age:"Très âgé (secret)",
  aff:"Camp Emilia (sponsor)", status:"Vivant", va:"Takehito Koyasu",
  abilities:["Maîtrise des six attributs","Magie de Feu surpuissante"],
  epi:"Le margrave excentrique",
  quote:"Touuut se déroule selon l'Évangile.",
  lead:"Roswaal L. Mathers est un margrave de Lugnica, mage le plus puissant du royaume, et le principal soutien financier et politique d'Emilia. Sous son maquillage de clown et son élocution traînante se cache un manipulateur redoutable.",
  sections:[
    {h:"Apparence", html:"Roswaal se présente maquillé en clown : fard blanc, lèvres marquées et surtout des yeux vairons — l'un jaune d'or, l'autre bleu. Chevelure indigo et tenues nobles extravagantes complètent une allure théâtrale, à l'image de son élocution traînante où il étire volontairement les voyelles."},
    {h:"Personnalité", html:"Courtois, cabotin et faussement nonchalant, Roswaal dissimule un esprit calculateur et une cruauté sans état d'âme. Tout, dans sa vie, est subordonné à un seul but ; il manipule son entourage — y compris ceux qui lui sont dévoués — comme les pièces d'un plan patiemment ourdi."},
    {h:"Le secret de sa longévité", html:"Le « Roswaal » que l'on connaît est bien plus âgé qu'il n'y paraît : à travers les générations, il perpétue lui-même sa lignée en transmettant son âme, afin de continuer à vivre en attendant un événement précis. Cette immortalité de fait fait de lui l'un des personnages les plus anciens du récit."},
    {h:"Motivations", html:"Roswaal vit selon un <em>Évangile</em>, livre de prophéties laissé par la Sorcière de l'Avarice Echidna, dont il espère obstinément le retour. Cette obsession le pousse à orchestrer dans l'ombre des événements cruels. À l'arc 4, ses prédictions cessent de se réaliser : contraint de parier sur Subaru, il est enfin confronté aux conséquences de sa foi aveugle."},
    {h:"Pouvoirs", html:"Roswaal est le mage le plus puissant du royaume de Lugnica. Fait rarissime, il maîtrise les six attributs magiques, avec une prédilection pour une magie de feu d'une puissance cataclysmique. Sa seule présence sur un champ de bataille suffit à en renverser l'issue."},
    {h:"Relations clés", html:"<strong>Ram</strong> — sa servante la plus dévouée, dont il connaît et exploite les sentiments. <strong>Beatrice</strong> — l'esprit laissé dans son manoir par Echidna. <strong>Echidna</strong> — la Sorcière disparue, objet de toute son existence. <strong>Emilia</strong> — sa candidate, qu'il soutient pour des raisons qui n'ont rien d'altruiste."},
  ],
  related:["beatrice","ram","echidna","emilia"],
},
{
  id:"frederica", name:"Frederica Baumann", kanji:"フレデリカ・バウマン", group:"roswaal",
  color:"#d99a4e", role:"Servante en chef", race:"Homme-bête", age:"Jeune femme",
  aff:"Camp Emilia", status:"Vivante", va:null,
  abilities:["Transformation bestiale","Force accrue"],
  epi:"La servante en chef aux crocs d'or",
  quote:"",
  lead:"Frederica Baumann est la servante en chef du manoir Roswaal, une femme-bête élégante reconnaissable à ses crocs. Sœur aînée de Garfiel, elle veille avec rigueur et bienveillance sur la maisonnée.",
  sections:[
    {h:"Apparence", html:"Grande et élégante, Frederica a de longs cheveux blonds et des yeux verts. Un détail la distingue : de longues canines pointues qu'elle juge peu féminines et qu'elle s'efforce longtemps de cacher, complexe hérité de son sang de femme-bête."},
    {h:"Personnalité", html:"Stricte, méthodique et exigeante dans son travail, Frederica se révèle profondément bienveillante et protectrice envers ceux dont elle a la charge. Servante en chef irréprochable, elle veille sur la maisonnée avec une rigueur qui masque une grande douceur."},
    {h:"Biographie", html:"Née au Sanctuaire, terre des demi-humains, Frederica en est sortie pour servir la maison Roswaal, laissant derrière elle son jeune frère Garfiel. Cette séparation et le sort du Sanctuaire pèsent lourdement sur elle et prennent une place centrale dans l'arc 4, lorsque Subaru s'y rend."},
    {h:"Pouvoirs & rôle", html:"En tant que femme-bête, Frederica peut se transformer partiellement en fauve, décuplant sa force et sa vitesse pour défendre le domaine. Au manoir, elle forme la jeune Petra au métier de servante et devient un pilier logistique du camp d'Emilia."},
    {h:"Relations clés", html:"<strong>Garfiel</strong> — son frère cadet, dont la réconciliation la bouleverse. <strong>Petra</strong> — sa protégée, qu'elle forme avec exigence et affection. <strong>Ram</strong> — sa collègue au service de Roswaal."},
  ],
  related:["garfiel","petra","ram"],
},
{
  id:"petra", name:"Petra Leyte", kanji:"ペトラ・ライテ", group:"roswaal",
  color:"#e58aa0", role:"Servante du village", race:"Humaine", age:"Enfant",
  aff:"Camp Emilia", status:"Vivante", va:null,
  abilities:["Couture","Vivacité d'esprit","Courage"],
  epi:"La jeune servante du village",
  quote:"",
  lead:"Petra Leyte est une fillette du village d'Earlham devenue servante au manoir Roswaal. Admirative de Subaru depuis l'arc 2, elle se révèle d'un courage étonnant pour son âge.",
  sections:[
    {h:"Apparence", html:"Petra est une fillette aux cheveux châtain clair et aux grands yeux vifs, la plus jeune de l'équipe du manoir. Elle porte fièrement son uniforme de servante, symbole de la place qu'elle s'est choisie."},
    {h:"Personnalité", html:"Éveillée, débrouillarde et d'une maturité surprenante pour son âge, Petra fait preuve d'un courage remarquable dans les moments de crise. Espiègle, elle assume ouvertement son admiration — teintée d'un premier amour — pour Subaru."},
    {h:"Biographie", html:"Originaire du village d'Earlham, Petra apparaît dès l'arc 2 : dans certaines boucles, elle compte parmi les enfants enlevés par l'assassin Elsa, ce qui marque durablement Subaru. Décidée à ne plus être une victime que l'on protège, elle rejoint le manoir comme servante et s'y forme auprès de Frederica."},
    {h:"Rôle", html:"Petra incarne les gens ordinaires que Subaru s'efforce de sauver. Loin d'être un simple faire-valoir, elle se montre observatrice et fiable, prête à tenir tête au danger pour défendre le domaine et ceux qu'elle aime."},
    {h:"Relations clés", html:"<strong>Frederica</strong> — sa mentore. <strong>Subaru</strong> — qu'elle admire profondément. <strong>Meili</strong> — avec qui elle se lie lorsque cette dernière est recueillie au manoir."},
  ],
  related:["frederica","meili","subaru"],
},
{
  id:"otto", name:"Otto Suwen", kanji:"オットー・スーウェン", group:"roswaal",
  color:"#8fae5a", role:"Marchand · Bras droit de Subaru", race:"Humain", age:"Jeune adulte",
  aff:"Camp Emilia", status:"Vivant", va:"Tomoaki Maeno",
  abilities:["Bénédiction du langage animal","Sens des affaires"],
  epi:"Le marchand au sang-froid",
  quote:"",
  lead:"Otto Suwen est un marchand itinérant devenu l'un des plus loyaux compagnons de Subaru et le stratège discret du camp Emilia.",
  sections:[
    {h:"Apparence", html:"Otto a des cheveux châtain-vert et une allure de marchand ordinaire, sans signe distinctif martial — ce qui contribue à le faire sous-estimer par ses adversaires comme par ses alliés."},
    {h:"Personnalité", html:"Pragmatique, débrouillard et affligé d'une malchance quasi comique, Otto masque sous ses jérémiades une intelligence tactique aiguë et une loyauté à toute épreuve. Il devient le meilleur ami de Subaru — l'un des rares à connaître sa détresse — et l'un des rares à oser lui tenir tête."},
    {h:"Sa Bénédiction", html:"Otto possède la <em>Bénédiction du langage divin</em> : il entend et comprend la voix des esprits, des animaux et des bêtes. Ce don, incontrôlable dans son enfance, l'a longtemps isolé, submergé par un vacarme permanent — mais il en fait plus tard un atout d'information redoutable."},
    {h:"Biographie & rôle", html:"Marchand itinérant, Otto rencontre Subaru lors de la chasse à la Baleine Blanche (arc 3) et finit par rallier le camp d'Emilia. À partir de l'arc 4, il en devient le stratège et le responsable des « affaires internes » : logistique, réseau, gestion — un rôle vital et pourtant discret."},
    {h:"Relations clés", html:"<strong>Subaru</strong> — son meilleur ami et complice. <strong>Garfiel</strong> — son compagnon d'armes. <strong>Roswaal</strong> — dont il se méfie à juste titre."},
  ],
  related:["subaru","garfiel","roswaal"],
},
{
  id:"garfiel", name:"Garfiel Tinsel", kanji:"ガーフィール・ティンゼル", group:"roswaal",
  color:"#d9b24a", role:"Combattant du Sanctuaire", race:"Demi-homme-bête", age:"≈ 14 ans",
  aff:"Camp Emilia", status:"Vivant", va:"Yūto Uemura",
  abilities:["Force surhumaine","Transformation bestiale","Crocs d'acier"],
  epi:"Le bouclier du Sanctuaire",
  quote:"",
  lead:"Garfiel Tinsel est un jeune combattant féroce du Sanctuaire, frère cadet de Frederica. Derrière sa rage et sa puissance brute se cache un enfant terrifié par l'abandon.",
  sections:[
    {h:"Apparence", html:"Garfiel est un adolescent musclé aux cheveux blonds hérissés et aux yeux verts, la bouche ornée de crocs proéminents et le visage barré d'une cicatrice. Son allure agressive trahit d'emblée sa nature de combattant."},
    {h:"Personnalité", html:"Fanfaron, impulsif et bagarreur, Garfiel dissimule derrière sa fureur une peur panique de l'abandon, née du départ inexpliqué de sa mère. Cette blessure le pousse à tout contrôler et à repousser ceux qui l'entourent, de crainte de les perdre."},
    {h:"Biographie", html:"Élevé au Sanctuaire, refuge scellé des demi-humains, Garfiel s'en est autoproclamé le gardien, empêchant quiconque d'en franchir la barrière. À l'arc 4, Subaru l'aide à affronter ses traumatismes et à pardonner ; libéré de ses peurs, Garfiel rejoint alors le camp d'Emilia."},
    {h:"Pouvoirs", html:"Doté d'une force surhumaine et d'une résistance hors norme, Garfiel peut se transformer en une puissante bête féline. Surnommé pour ses « crocs d'acier », il devient l'un des meilleurs combattants au corps-à-corps du camp d'Emilia."},
    {h:"Relations clés", html:"<strong>Frederica</strong> — sa sœur aînée, dont les retrouvailles le bouleversent. <strong>Ram</strong> — pour qui il développe des sentiments dans les arcs ultérieurs. <strong>Subaru</strong> — l'homme qui a brisé sa prison intérieure. <strong>Ryuzu</strong> — figure tutélaire du Sanctuaire."},
  ],
  related:["frederica","subaru","ram"],
},
{
  id:"ryuzu", name:"Ryuzu Meyer", kanji:"リューズ・メイエル", group:"roswaal",
  color:"#9ad1c0", role:"Gardienne du Sanctuaire", race:"Demi-humaine (originelle)", age:"≈ 400 ans (apparence enfantine)",
  aff:"Sanctuaire → Camp Emilia", status:"Vivante", va:null,
  abilities:["Maintien de la barrière du Sanctuaire","Réplicas (clones)"],
  epi:"L'aïeule du Sanctuaire",
  quote:"",
  lead:"Ryuzu Meyer est la gardienne et figure fondatrice du Sanctuaire, l'enclave scellée des demi-humains. Sous les traits d'une fillette aux cheveux verts, elle veille depuis des siècles sur le refuge et ses habitants.",
  sections:[
    {h:"Nature & clones", html:"L'originelle Ryuzu Meyer sommeille au cœur du Sanctuaire, reliée à un immense cristal. De cette source naissent d'innombrables réplicas identiques — Ryuzu Bilma, Ryuzu Shima… — qui administrent le refuge et en maintiennent la barrière. Leur existence est intimement liée aux travaux de la Sorcière de l'Avarice, Echidna."},
    {h:"Rôle", html:"D'un calme bienveillant, Ryuzu guide Subaru et les habitants durant l'arc 4. Après la résolution de la crise du Sanctuaire, elle et les siens se rangent aux côtés du camp d'Emilia, apportant leur savoir et leur soutien."},
    {h:"Relations clés", html:"<strong>Garfiel</strong> et <strong>Frederica</strong> — enfants du Sanctuaire qu'elle a vus grandir. <strong>Echidna</strong> — la Sorcière dont son existence même découle. <strong>Beatrice</strong> — une autre création liée à la même époque."},
  ],
  related:["garfiel","echidna","beatrice"],
},
{
  id:"patrasche", name:"Patrasche", kanji:"パトラッシュ", group:"roswaal",
  color:"#6b6f7a", role:"Dragon-terre de Subaru", race:"Dragon terrestre", age:"—",
  aff:"Camp Emilia", status:"Vivante", va:null,
  abilities:["Vitesse & endurance","Loyauté absolue"],
  epi:"La fidèle monture de Subaru",
  quote:"",
  lead:"Patrasche est la dragonne-terre attribuée à Subaru, une monture d'une intelligence et d'une loyauté exceptionnelles qui devient l'une de ses plus fidèles compagnes.",
  sections:[
    {h:"Apparence", html:"Patrasche est un dragon terrestre à l'imposante robe sombre, aux écailles luisantes et au regard étonnamment expressif. Sa carrure puissante contraste avec la douceur qu'elle réserve à son cavalier."},
    {h:"Loyauté légendaire", html:"Dragon terrestre au tempérament farouche, Patrasche s'attache profondément à Subaru et lui sauve la vie à d'innombrables reprises, allant jusqu'au sacrifice dans certaines boucles pour le protéger. Elle incarne, aux yeux des fans, le symbole même de la fidélité dans Re:Zero."},
    {h:"Rôle", html:"Rapide et endurante, bénéficiant de la Bénédiction du Dragon Terrestre, Patrasche permet à Subaru — dépourvu de puissance de combat — de se déplacer et de fuir ou charger sur le champ de bataille. Son lien silencieux avec lui compte parmi les relations les plus touchantes de la série."},
  ],
  related:["subaru"],
},
/* ===== SÉLECTION ROYALE ===== */
{
  id:"felt", name:"Felt", kanji:"フェルト", group:"royale",
  color:"#f0c050", role:"Candidate au trône", race:"Humaine", age:"≈ 15 ans",
  aff:"Camp Felt", status:"Vivante", va:"Chinatsu Akasaki",
  abilities:["Agilité","Vol (larcin)","Sang royal caché"],
  epi:"La voleuse devenue candidate",
  quote:"",
  lead:"Felt est une gamine des bas-fonds de la capitale, voleuse au franc-parler, dont le sang révèle une ascendance royale. Elle devient l'une des cinq candidates à la Sélection Royale.",
  sections:[
    {h:"Apparence", html:"Felt est une adolescente menue aux courts cheveux blonds et aux yeux rouges, vêtue comme une gamine des rues. Son allure de garçon manqué contraste avec le sang royal qui coule dans ses veines."},
    {h:"Personnalité", html:"Débrouillarde, franche et rétive à toute autorité, Felt a grandi seule dans les bas-fonds et méprise les hiérarchies figées. Elle rejette d'abord violemment l'idée de devenir reine, mais son sens aigu de la justice et de la liberté finit par en faire une candidate sincère."},
    {h:"Biographie", html:"Voleuse survivant dans les taudis de la capitale, Felt se retrouve mêlée à l'affaire de l'insigne volé dès la première boucle de Subaru. Lorsque son sang révèle une ascendance royale, elle est propulsée dans la Sélection Royale et confiée à Reinhard, qui se lie à elle en tant que chevalier."},
    {h:"Idéal & entourage", html:"Felt rêve d'un royaume où le mérite l'emporte sur la naissance et où les faibles ne sont plus écrasés. Elle est escortée par <strong>Reinhard van Astrea</strong>, le plus puissant chevalier de Lugnica, et protégée de longue date par le vieux receleur Rom."},
  ],
  related:["reinhard","elsa"],
},
{
  id:"crusch", name:"Crusch Karsten", kanji:"クルシュ・カルステン", group:"royale",
  color:"#2ea36b", role:"Candidate au trône", race:"Humaine", age:"Jeune adulte",
  aff:"Camp Crusch", status:"Vivante", va:"Yōko Hikasa",
  abilities:["Épée du Vent","Discernement (Bénédiction)"],
  epi:"La duchesse au sabre de vent",
  quote:"",
  lead:"Crusch Karsten est une duchesse droite et honorable, candidate au trône, qui prône une rupture avec la dépendance du royaume au Dragon et l'autodétermination de Lugnica.",
  sections:[
    {h:"Apparence", html:"Crusch a de longs cheveux verts et des yeux ambrés ; elle porte souvent une tenue masculine d'apparat, reflet de sa volonté de s'imposer dans un monde d'hommes. Sa prestance en fait une cheffe naturelle."},
    {h:"Personnalité", html:"Droite, honorable et intransigeante avec elle-même, Crusch place le devoir et l'honnêteté au-dessus de tout. Elle prône l'autodétermination du royaume, libéré de sa dépendance au Dragon — une position audacieuse qui rompt avec des siècles de tradition."},
    {h:"Pouvoirs", html:"Duelliste d'exception, Crusch manie une magie du vent tranchante et possède la <em>Bénédiction du Vent Révélateur</em>, qui lui fait « voir » les mensonges sous forme de perturbations. Ces atouts en font une adversaire redoutable comme une négociatrice implacable."},
    {h:"Rôle & tragédie", html:"Alliée décisive de Subaru lors de la chasse à la Baleine Blanche (arc 3), Crusch subit ensuite une perte cruelle : l'Archevêque de la Gourmandise dévore son nom et ses souvenirs, la laissant amnésique. Son entourage, Ferris et Wilhelm en tête, se bat pour la lui rendre."},
    {h:"Relations clés", html:"<strong>Felix « Ferris »</strong> — son chevalier et ami d'enfance, d'une loyauté absolue. <strong>Wilhelm</strong> — son majordome et bras armé. <strong>Subaru</strong> — allié de circonstance devenu ami."},
  ],
  related:["felix","wilhelm","subaru"],
},
{
  id:"priscilla", name:"Priscilla Barielle", kanji:"プリシラ・バーリエル", group:"royale",
  color:"#d64a4a", role:"Candidate au trône", race:"Humaine", age:"Jeune adulte",
  aff:"Camp Priscilla", status:"Vivante", va:"Marie Miyake",
  abilities:["Épée Yang","Sang du soleil (Yang)"],
  epi:"La candidate flamboyante",
  quote:"",
  lead:"Priscilla Barielle est une noble orgueilleuse et impériale, persuadée que le monde existe pour la servir — et souvent assez puissante pour le prouver.",
  sections:[
    {h:"Apparence", html:"Priscilla a de longs cheveux orangés et un port altier, vêtue de robes somptueuses évoquant le soleil. Son sourire dédaigneux et son éventail sont devenus sa signature."},
    {h:"Personnalité", html:"Orgueilleuse jusqu'à l'excès, Priscilla est convaincue que le monde tourne autour d'elle — « tout ce qui compte finit par lui revenir ». Cette arrogance cache pourtant une forme de générosité brutale et une lucidité tranchante sur la nature humaine."},
    {h:"Pouvoirs", html:"Priscilla manie le <em>Yang Sword</em>, une lame qui matérialise sa propre puissance, et son sang possède des propriétés liées à l'attribut Yang (chaleur, feu du soleil). Combattante d'un niveau redoutable, elle n'a besoin que rarement d'être défendue."},
    {h:"Rôle & entourage", html:"Escortée par l'énigmatique chevalier masqué <strong>Al</strong>, Priscilla prend une importance croissante dans les arcs impériaux de Vollachia, où ses origines et ses ambitions se révèlent bien plus vastes qu'il n'y paraissait."},
  ],
  related:["al"],
},
{
  id:"anastasia", name:"Anastasia Hoshin", kanji:"アナスタシア・ホーシン", group:"royale",
  color:"#7a5cc0", role:"Candidate au trône", race:"Humaine", age:"Jeune adulte",
  aff:"Camp Anastasia", status:"Vivante", va:"Inori Minase",
  abilities:["Esprit Echidna (écharpe)","Sens du commerce"],
  epi:"La marchande ambitieuse",
  quote:"",
  lead:"Anastasia Hoshin est une magnate du commerce originaire des Cités-États de Kararagi, candidate au trône par avidité assumée — elle « veut tout posséder », y compris une nation.",
  sections:[
    {h:"Apparence", html:"Anastasia a de longs cheveux lilas et un regard malicieux ; son écharpe en fourrure blanche, qu'elle ne quitte jamais, est bien plus qu'un accessoire de mode."},
    {h:"Personnalité", html:"Souriante et affable en surface, Anastasia est avant tout une redoutable femme d'affaires au franc-parler teinté du dialecte de Kararagi. Son ambition, elle l'assume sans détour : « je veux tout posséder » — y compris une nation entière."},
    {h:"L'esprit de l'écharpe", html:"Son écharpe abrite un esprit artificiel nommé <em>Echidna</em> (homonyme de la Sorcière de l'Avarice), qui lui prête conseil et pouvoir. Ce lien devient central dans l'arc 6, à la Tour de Pleiades, où l'identité même d'Anastasia est mise en jeu."},
    {h:"Rôle & entourage", html:"Originaire des Cités-États marchandes de Kararagi, Anastasia bâtit sa candidature sur son empire commercial. Elle est servie par <strong>Julius Juukulius</strong>, l'un des chevaliers les plus accomplis du royaume."},
  ],
  related:["julius"],
},
/* ===== CHEVALIERS ===== */
{
  id:"reinhard", name:"Reinhard van Astrea", kanji:"ラインハルト・ヴァン・アストレア", group:"chevaliers",
  color:"#e7c873", role:"Sword Saint · Chevalier de Felt", race:"Humain", age:"≈ 18 ans",
  aff:"Camp Felt", status:"Vivant", va:"Yūichi Nakamura",
  abilities:["Bénédictions divines innombrables","Épée du Dragon, Reid","Maîtrise absolue de l'épée"],
  epi:"Le Sword Saint, le plus fort de Lugnica",
  quote:"Tant que je tiens debout, personne ne mourra ici.",
  lead:"Reinhard van Astrea est le <strong>Sword Saint</strong> (Maître d'Épée) et l'être le plus puissant du royaume de Lugnica. Héritier de la prestigieuse lignée Astrea, il cumule un nombre quasi infini de Bénédictions Divines.",
  sections:[
    {h:"Puissance", html:"Doté de dons divins (Soleil, Vent, résurrection du Phénix, détection du danger…) et seul digne de dégainer l'Épée du Dragon Reid, Reinhard n'a jamais été vaincu en combat loyal dans le récit principal. Sa simple présence réécrit l'issue d'une bataille."},
    {h:"Tragédie", html:"Derrière sa perfection se cache le poids d'un héritage douloureux : la mort de sa grand-mère Theresia, précédente Sword Saint, et les rapports brisés au sein de la famille Astrea. Reinhard ne cherche jamais la gloire — toute sa force n'a qu'un but : que personne, autour de lui, n'ait plus jamais à mourir."},
    {h:"Apparence", html:"Grand, athlétique, Reinhard arbore d'éclatants cheveux rouges et des yeux bleu ciel, revêtu de l'uniforme des Chevaliers Royaux. Sa prestance en impose immédiatement, à la hauteur de sa réputation de plus grand héros vivant du royaume."},
    {h:"L'ombre de l'Épée du Dragon", html:"Reinhard peut invoquer l'<em>Épée du Dragon Reid</em>, arme sacrée qu'il est le seul digne de manier — mais il refuse de la dégainer, considérant que le faire signerait son échec à protéger sans elle. Cette retenue résume le personnage : une puissance quasi divine constamment bridée par l'humilité et le devoir."},
    {h:"Les Bénédictions Divines", html:"La force de Reinhard ne vient pas du mana mais d'un nombre proprement incalculable de <em>Bénédictions Divines</em>, dons innés qu'il accumule au point d'en ignorer certaines. Parmi les plus connues : la Bénédiction du Soleil, celle du Vent, la détection du danger, une force et une vitesse surhumaines, et surtout celle du <em>Phénix</em>, qui le ressuscite tant que la condition de sa mort n'est pas comprise. Cet arsenal le rend, de fait, invincible dans le récit principal."},
    {h:"Le fardeau des Astrea", html:"La famille Astrea porte une malédiction née de la façon dont Reinhard « hérita » du titre de Sword Saint, arrachant involontairement son pouvoir à sa grand-mère Theresia — un drame qui coûta la vie de cette dernière et brisa son grand-père Wilhelm comme son père Heinkel. Toute la puissance de Reinhard est ainsi indissociable d'une culpabilité familiale qu'il porte en silence."},
    {h:"Relations clés", html:"<strong>Felt</strong> — sa maîtresse et candidate, à qui il s'est lié par la Bénédiction du sang royal. <strong>Wilhelm</strong> — son grand-père, l'Épéiste. <strong>Theresia</strong> — sa grand-mère, la précédente Sword Saint. <strong>Subaru</strong> — qu'il respecte pour son courage face à l'impossible."},
  ],
  related:["felt","wilhelm","theresia","subaru"],
},
{
  id:"felix", name:"Felix « Ferris » Argyle", kanji:"フェリックス・アーガイル", group:"chevaliers",
  color:"#2bbf9e", role:"Chevalier de Crusch", race:"Homme-bête (chat)", age:"Jeune adulte",
  aff:"Camp Crusch", status:"Vivant", va:"Yumiri Hanamori",
  abilities:["Magie de soin suprême (Eau)"],
  epi:"Le plus grand guérisseur du royaume",
  quote:"",
  lead:"Felix Argyle, surnommé « Ferris », est le chevalier de Crusch et le meilleur guérisseur du royaume, reconnaissable à son apparence féline et à sa tenue espiègle.",
  sections:[
    {h:"Apparence", html:"Felix, dit « Ferris », a des cheveux châtain clair, des oreilles et une queue de chat, et s'habille de manière volontairement féminine. Son allure espiègle masque l'un des esprits les plus sérieux du royaume."},
    {h:"Personnalité", html:"Taquin, coquet et d'un naturel enjoué, Ferris parle de lui à la manière d'un chat (« -nya »). Derrière cette légèreté se cache une détermination de fer et un dévouement absolu envers Crusch, pour qui il serait prêt à tout."},
    {h:"Pouvoirs", html:"Ferris est tout simplement le plus grand guérisseur du royaume : sa maîtrise de la magie de l'eau confine au miracle. Il peut sauver des blessés condamnés — mais aussi, en connaissant si intimement le corps, en faire une arme mortelle. Il ne combat toutefois pas offensivement, refusant d'ôter la vie."},
    {h:"Relations clés", html:"<strong>Crusch</strong> — sa maîtresse et amie d'enfance, le centre de son existence. <strong>Wilhelm</strong> — son aîné au sein de la maison Karsten. <strong>Subaru</strong> — qu'il soigne et épaule durant l'arc 3."},
  ],
  related:["crusch","wilhelm","subaru"],
},
{
  id:"julius", name:"Julius Juukulius", kanji:"ユリウス・ユークリウス", group:"chevaliers",
  color:"#c9a23a", role:"Chevalier d'Anastasia", race:"Humain", age:"Jeune adulte",
  aff:"Camp Anastasia", status:"Vivant", va:null,
  abilities:["Pacte avec six quasi-esprits","Escrime raffinée"],
  epi:"Le Chevalier le plus fin",
  quote:"",
  lead:"Julius Juukulius est un chevalier-esprit exemplaire au service d'Anastasia, surnommé « le plus fin des chevaliers » pour son élégance et sa maîtrise.",
  sections:[
    {h:"Apparence", html:"Julius a des cheveux violets soigneusement coiffés et une élégance irréprochable, en parfait chevalier de cour. Une balafre discrète rappelle qu'il n'est pas qu'un homme de salon."},
    {h:"Personnalité", html:"Courtois, exemplaire et exigeant envers lui-même, Julius incarne l'idéal chevaleresque. Sa politesse constante peut passer pour de la froideur, mais elle recouvre un sens de l'honneur profond et une loyauté indéfectible."},
    {h:"Pouvoirs", html:"Julius est un mage-esprit lié par contrat à six quasi-esprits élémentaires (les « Sesquialtera »), qu'il combine à une escrime raffinée pour un style de combat unique. Il est réputé « le plus fin des chevaliers » du royaume."},
    {h:"Rôle", html:"Adversaire de Subaru lors de leur première rencontre houleuse (arc 3), Julius devient peu à peu un allié de confiance. À l'arc 6, son propre nom est dévoré par la Gourmandise et oublié de tous sauf de Subaru — un fardeau qu'ils portent ensemble à la Tour de Pleiades."},
  ],
  related:["anastasia","subaru"],
},
{
  id:"wilhelm", name:"Wilhelm van Astrea", kanji:"ヴィルヘルム・ヴァン・アストレア", group:"chevaliers",
  color:"#8a98b5", role:"Épéiste · Maison Crusch", race:"Humain", age:"Âgé",
  aff:"Camp Crusch", status:"Vivant", va:"Tsutomu Isobe",
  abilities:["Maîtrise absolue de l'épée","Surnommé « le Démon de l'Épée »"],
  epi:"L'Épéiste, le Démon de l'Épée",
  quote:"",
  lead:"Wilhelm van Astrea est un majordome et épéiste vétéran au service de Crusch, jadis surnommé le « Démon de l'Épée ». Veuf de Theresia, la précédente Sword Saint, il est aussi le grand-père de Reinhard.",
  sections:[
    {h:"Apparence", html:"Wilhelm est un vieil homme aux cheveux blancs, à la posture impeccable de majordome et au regard d'acier. Rien, dans son maintien policé, ne trahit d'emblée le tueur légendaire qu'il fut."},
    {h:"Personnalité", html:"Digne, discipliné et d'une politesse sans faille, Wilhelm cache une douleur immense et une soif de vengeance patiemment contenue. Son amour pour sa défunte épouse, Theresia, guide chacun de ses actes."},
    {h:"Le Démon de l'Épée", html:"Dans sa jeunesse, Wilhelm était surnommé le « Démon de l'Épée » pour sa maîtrise inégalée. Roturier, il tomba amoureux de Theresia, la Sword Saint qui haïssait l'épée — et jura de se battre à sa place pour qu'elle puisse déposer la sienne."},
    {h:"Vengeance", html:"Lorsque la Baleine Blanche lui arrache Theresia, Wilhelm consacre des années à traquer le fléau. Son duel contre le monstre, à l'arc 3 aux côtés de Subaru et de Crusch, est l'un des sommets émotionnels de la série — l'aboutissement d'un deuil et d'une promesse."},
    {h:"Relations clés", html:"<strong>Theresia</strong> — son épouse, la précédente Sword Saint. <strong>Reinhard</strong> — son petit-fils, avec qui les rapports sont brisés par le drame familial. <strong>Crusch</strong> — sa maîtresse, qu'il sert avec dévouement."},
  ],
  related:["theresia","reinhard","crusch"],
},
/* ===== SORCIÈRES & CULTE ===== */
{
  id:"satella", name:"Satella", kanji:"サテラ", group:"sorcieres",
  color:"#8b5cf6", role:"Sorcière de l'Envie", race:"Demi-elfe (Sorcière)", age:"≈ 400 ans",
  aff:"Sorcières des Péchés", status:"Scellée", va:"Rie Takahashi",
  abilities:["Pouvoirs de toutes les Sorcières des Péchés","Lien avec le Return by Death"],
  epi:"La Sorcière de l'Envie",
  quote:"Je t'aime. Je t'aime. Je t'aime. Je t'aime…",
  lead:"Satella est la Sorcière de l'Envie, l'entité la plus redoutée du monde de Re:Zero. Il y a quatre siècles, elle aurait dévoré les six autres Sorcières des Péchés et menacé d'engloutir le monde, avant d'être scellée.",
  sections:[
    {h:"Mystère", html:"Demi-elfe argentée dont Emilia partage l'apparence, Satella est liée d'une manière obscure au Return by Death de Subaru : c'est son « ombre » qui le punit lorsqu'il tente de révéler son pouvoir. Son amour obsessionnel et destructeur pour Subaru est l'un des plus grands mystères du récit."},
    {h:"La Sorcière de l'Envie", html:"Il y a environ quatre siècles, Satella aurait absorbé les six autres Sorcières des Péchés et menacé d'engloutir le monde, avant d'être scellée par le Dragon, le Sword Saint et un grand sage. Le Culte des Sorcières œuvre depuis à sa résurrection. La distinction entre « Satella » et l'Envie qui la posséderait reste l'une des grandes énigmes de l'œuvre."},
    {h:"Lien avec Emilia", html:"La ressemblance entre Emilia et Satella n'est pas fortuite : elle nourrit la haine du royaume envers Emilia et alimente les théories des lecteurs. Le fait que la même comédienne, Rie Takahashi, prête sa voix aux deux renforce ce trouble volontairement entretenu par l'auteur."},
  ],
  related:["emilia","subaru","echidna"],
},
{
  id:"echidna", name:"Echidna", kanji:"エキドナ", group:"sorcieres",
  color:"#c9c2d6", role:"Sorcière de l'Avarice", race:"Sorcière (esprit)", age:"Morte (esprit)",
  aff:"Sorcières des Péchés", status:"Décédée · esprit", va:"Maaya Sakamoto",
  abilities:["Savoir absolu","Salon des Sorcières","Création d'esprits artificiels"],
  epi:"La Sorcière de l'Avarice (du savoir)",
  quote:"",
  lead:"Echidna est la Sorcière de l'Avarice, mue non par la cupidité matérielle mais par une soif inextinguible de connaissance. Hôtesse du « Salon des Sorcières », elle apparaît à Subaru dans des espaces oniriques.",
  sections:[
    {h:"Rôle", html:"Créatrice de Beatrice et des Évangiles, Echidna manipule Roswaal et tente de séduire Subaru par le savoir, lui offrant un pacte qu'il refuse. Charmante et glaçante, elle incarne le danger de la curiosité sans limite morale."},
    {h:"Le Salon des Sorcières", html:"Bien que morte depuis des siècles, la conscience d'Echidna subsiste dans la Tombe du Sanctuaire, où elle reçoit Subaru autour d'un « thé » — un espace onirique. Elle y côtoie les âmes résiduelles des autres Sorcières des Péchés (Minerva, Daphne, Typhon, Sekhmet, Carmilla), offrant certaines des scènes les plus fascinantes de l'arc 4."},
    {h:"Apparence", html:"Echidna a de longs cheveux blancs, une peau très pâle et des yeux aux iris noirs marqués d'un motif clair. Sa voix posée et son sourire imperturbable dissimulent une froideur absolue : pour elle, toute vie n'est qu'un objet d'étude."},
  ],
  related:["beatrice","roswaal","satella"],
},
{
  id:"betelgeuse", name:"Betelgeuse Romanée-Conti", kanji:"ベテルギウス・ロマネコンティ", group:"sorcieres",
  color:"#7a7a7a", role:"Archevêque de la Paresse", race:"Humain", age:"Adulte",
  aff:"Culte des Sorcières", status:"Décédé", va:"Takehito Koyasu",
  abilities:["Invisible Providence (Mains invisibles, Yin)"],
  epi:"L'Archevêque de la Paresse",
  quote:"",
  lead:"Betelgeuse Romanée-Conti est un Archevêque du Péché de la Paresse, fanatique dément du Culte des Sorcières et premier grand ennemi vaincu par Subaru.",
  sections:[
    {h:"Apparence", html:"Betelgeuse est un homme émacié aux longs cheveux noirs et aux yeux cernés, dont le corps se contorsionne dans des postures grotesques et inhumaines lorsqu'il se laisse envahir par sa « diligence »."},
    {h:"Personnalité", html:"Fanatique dément, Betelgeuse vénère la Sorcière de l'Envie d'un amour maladif et se croit investi d'une mission sacrée. Ses accès de folie, ponctués du mot « diligence », en font l'un des antagonistes les plus dérangeants de la série."},
    {h:"Pouvoir", html:"Son Authorité, l'<em>Invisible Providence</em>, déploie des « Mains invisibles » capables de broyer et d'empaler ce qu'elles saisissent. Il peut en outre transférer son esprit dans d'autres corps, ce qui le rend extrêmement difficile à tuer définitivement."},
    {h:"Rôle", html:"Chef de file du Culte lors de l'assaut sur le domaine Roswaal, Betelgeuse est le premier grand ennemi que Subaru parvient à vaincre (arc 3), au terme d'un plan élaboré qui retourne son propre pouvoir contre lui. Sa chute marque le premier vrai triomphe de Subaru."},
  ],
  related:["sirius","satella"],
},
{
  id:"regulus", name:"Regulus Corneas", kanji:"レグルス・コルニアス", group:"sorcieres",
  color:"#c9b24a", role:"Archevêque de l'Avarice", race:"Humain", age:"Adulte",
  aff:"Culte des Sorcières", status:"Vaincu", va:null,
  abilities:["Le Monde Immobile (invulnérabilité)"],
  epi:"L'Archevêque de l'Avarice",
  quote:"",
  lead:"Regulus Corneas est l'Archevêque du Péché de l'Avarice, tyran narcissique aux dizaines d'« épouses » qu'il considère comme des possessions.",
  sections:[
    {h:"Apparence", html:"Regulus a de courts cheveux blancs et un regard morne. Son apparence banale et sa voix geignarde masquent l'un des adversaires les plus meurtriers du récit."},
    {h:"Personnalité", html:"Narcissique absolu, Regulus exige un monde « sans le moindre accroc » à sa tranquillité et considère ses dizaines d'« épouses » comme de simples possessions. La moindre contrariété déclenche chez lui une rage disproportionnée et une logique tordue où il se pose toujours en victime."},
    {h:"Pouvoir", html:"Son Authorité, « Le Monde Immobile », fige l'état de son corps : tant qu'il retient son souffle, rien ne peut l'altérer — ni le blesser, ni le déplacer. Il peut de plus figer le « temps » du cœur de ses épouses, faisant d'elles des bombes vivantes. Une invulnérabilité qui semble parfaite… jusqu'à ce qu'on en trouve la faille."},
    {h:"Chute", html:"À Pristella (arc 5), Regulus est vaincu grâce à l'ingéniosité combinée de Subaru, d'Emilia et de leurs alliés, qui exploitent la condition secrète de son invulnérabilité. L'une des victoires les plus satisfaisantes de la série."},
  ],
  related:["capella","sirius"],
},
{
  id:"capella", name:"Capella Emerada Lugunica", kanji:"カペラ・エメラダ・ルグニカ", group:"sorcieres",
  color:"#c0466a", role:"Archevêque de la Luxure", race:"Hybride (dragon)", age:"Inconnu",
  aff:"Culte des Sorcières", status:"En fuite", va:null,
  abilities:["Transformation par malédiction"],
  epi:"L'Archevêque de la Luxure",
  quote:"",
  lead:"Capella Emerada Lugunica est l'Archevêque du Péché de la Luxure, d'une cruauté sans limite, capable de transformer ses victimes — et elle-même — en monstres.",
  sections:[
    {h:"Apparence", html:"Capella apparaît sous les traits d'une jeune fille aux cheveux dorés à l'air innocent — un masque qu'elle abandonne pour révéler une hybride reptilienne au sang de dragon lorsqu'elle libère son pouvoir."},
    {h:"Personnalité", html:"D'une cruauté et d'un sadisme sans limite, Capella humilie et mutile ses victimes avec un plaisir manifeste. Elle est unanimement considérée comme l'une des figures les plus abjectes de tout Re:Zero."},
    {h:"Pouvoir", html:"Son Authorité de la Luxure lui permet de transformer, d'un simple contact ou d'un ordre, n'importe quel être vivant en créature difforme et monstrueuse — y compris son propre corps, qu'elle régénère et remodèle à volonté, la rendant quasi impossible à tuer."},
    {h:"Rôle", html:"Lors de l'assaut de Pristella (arc 5), Capella sème un chaos sanglant en transformant des habitants en monstres. Contrairement à Regulus, elle parvient à s'échapper, demeurant une menace latente."},
  ],
  related:["regulus","sirius"],
},
{
  id:"sirius", name:"Sirius Romanée-Conti", kanji:"シリウス・ロマネコンティ", group:"sorcieres",
  color:"#b0b0c0", role:"Archevêque de la Colère", race:"Humaine", age:"Adulte",
  aff:"Culte des Sorcières", status:"Capturée", va:null,
  abilities:["Contamination émotionnelle"],
  epi:"L'Archevêque de la Colère",
  quote:"",
  lead:"Sirius Romanée-Conti est l'Archevêque du Péché de la Colère, fanatique se proclamant « épouse » de Betelgeuse.",
  sections:[
    {h:"Apparence", html:"Sirius est entièrement enveloppée de bandages, telle une momie, et traîne de lourdes chaînes. Son apparence inquiétante reflète l'instabilité de son esprit."},
    {h:"Personnalité", html:"Fanatique se proclamant l'« épouse » de Betelgeuse, Sirius oscille entre une tendresse dévorante et une fureur destructrice. Elle prétend agir « par amour », ce qui rend son fanatisme d'autant plus terrifiant."},
    {h:"Pouvoir", html:"Son Authorité de la Colère provoque une contamination émotionnelle : les sentiments d'une personne — peur, haine, douleur — se propagent et s'amplifient instantanément à toute une foule. En prenant des otages, elle transforme la population entière de Pristella en une arme contre elle-même."},
    {h:"Rôle", html:"L'une des principales assaillantes de Pristella (arc 5). Après un affrontement où l'empathie et la coordination des héros l'emportent sur la haine collective, Sirius est finalement neutralisée et capturée."},
  ],
  related:["betelgeuse","capella"],
},
{
  id:"ley", name:"Ley Batenkaitos", kanji:"ライ・バテンカイトス", group:"sorcieres",
  color:"#7fae6a", role:"Archevêque de la Gourmandise", race:"Humain", age:"Inconnu",
  aff:"Culte des Sorcières", status:"Vaincu", va:null,
  abilities:["Dévorer les noms & les souvenirs"],
  epi:"L'Archevêque de la Gourmandise",
  quote:"",
  lead:"Ley Batenkaitos est l'un des trois frères qui se partagent le Péché de la Gourmandise, un dévoreur de « noms » et de « souvenirs ».",
  sections:[
    {h:"Apparence", html:"Ley a de courts cheveux blancs et un sourire perpétuel, extatique et dérangeant, propre à celui qui « savoure » chaque instant. Il change de manières selon la « personnalité » qu'il a récemment dévorée."},
    {h:"Personnalité", html:"Vorace et exalté, Ley aborde le meurtre comme un gastronome aborde un festin. Il incarne l'aspect « gourmet » du Péché de la Gourmandise, se délectant des identités qu'il consume."},
    {h:"Pouvoir", html:"Ley partage le Péché de la Gourmandise avec ses frères Roy et Louis. En dévorant le <em>nom</em> d'une victime, il l'efface de la mémoire de tous ; en dévorant ses <em>souvenirs</em>, il la plonge dans un sommeil sans fin. Il assimile aussi les capacités de ceux qu'il consume."},
    {h:"Rôle", html:"C'est Ley qui a dérobé le nom et les souvenirs de Rem, déclenchant l'un des plus longs fils rouges de l'œuvre. Traqué à travers plusieurs arcs, il est finalement vaincu durant la guerre de Vollachia (arc 8)."},
  ],
  related:["rem"],
},
{
  id:"pandora", name:"Pandora", kanji:"パンドラ", group:"sorcieres",
  color:"#cfc4e0", role:"Sorcière de la Vanité", race:"Sorcière", age:"Inconnu",
  aff:"Sorcière (indépendante)", status:"Inconnu", va:null,
  abilities:["Manipulation de la réalité"],
  epi:"La Sorcière de la Vanité",
  quote:"",
  lead:"Pandora est la Sorcière de la Vanité, une entité souriante et glaçante capable de réécrire les faits à volonté.",
  sections:[
    {h:"Apparence", html:"Pandora a l'apparence d'une jeune femme angélique aux longs cheveux blancs, au sourire doux et serein — une douceur qui rend sa cruauté d'autant plus glaçante."},
    {h:"Personnalité", html:"Calme, polie et impénétrable, Pandora poursuit ses objectifs avec une sérénité absolue, indifférente à la souffrance qu'elle provoque. Elle ne hausse jamais le ton : la réalité plie simplement à sa volonté."},
    {h:"Pouvoir", html:"Son Authorité lui permet de réécrire les faits et la réalité à volonté : annuler un événement, se rendre invulnérable, altérer les souvenirs. Cette maîtrise du réel en fait l'une des entités les plus déstabilisantes et dangereuses de l'univers."},
    {h:"Rôle", html:"Pandora est la grande responsable de la tragédie de la forêt d'Elior : c'est elle qui, un siècle plus tôt, a mené l'attaque ayant coûté la vie à Fortuna, la mère adoptive d'Emilia, et gelé le village. Elle demeure une antagoniste dont les buts profonds restent en partie mystérieux."},
  ],
  related:["emilia"],
},
/* ===== VOLLACHIA ===== */
{
  id:"vincent", name:"Vincent Vollachia", kanji:"ヴィンセント・ヴォラキア", group:"vollachia",
  color:"#b8323a", role:"Empereur de Vollachia", race:"Humain", age:"Jeune adulte",
  aff:"Empire de Vollachia", status:"Vivant", va:null,
  abilities:["Stratégie","Autorité impériale","Maîtrise martiale"],
  epi:"L'empereur de Vollachia",
  quote:"",
  lead:"Vincent Vollachia est l'empereur du Saint Empire de Vollachia, souverain brillant, froid et impitoyable, allié central de Subaru durant les arcs impériaux (7 à 9).",
  sections:[
    {h:"Apparence", html:"Vincent a de longs cheveux noirs et un regard perçant, une prestance impériale froide et calculée. Durant sa cavale, il se dissimule sous le nom d'« Abel »."},
    {h:"Personnalité", html:"Brillant, impitoyable et d'un pragmatisme glacial, Vincent applique jusqu'au bout la devise de Vollachia : « seul le plus fort règne ». Sa dureté cache toutefois une vision réelle du bien de son empire, quitte à sacrifier son propre confort — voire sa réputation."},
    {h:"Pouvoirs & atouts", html:"Vincent n'est pas un guerrier surpuissant mais un stratège hors pair, dont l'intelligence et l'autorité valent une armée. Sa capacité à anticiper ses adversaires en fait l'un des esprits les plus redoutables du continent."},
    {h:"Rôle", html:"Empereur renversé par un complot au sein même de son entourage, Vincent fait équipe avec Subaru et une coalition improbable pour reconquérir son trône (arcs 7 à 9). Leur alliance, née de la méfiance, devient l'un des moteurs des arcs impériaux."},
  ],
  related:["subaru"],
},
/* ===== AUTRES ===== */
{
  id:"elsa", name:"Elsa Granhiert", kanji:"エルザ・グランヒルテ", group:"autres",
  color:"#b6324a", role:"Assassin", race:"Humaine", age:"Adulte",
  aff:"Mercenaire", status:"Vivante", va:null,
  abilities:["Couteaux (kukri)","Régénération anormale"],
  epi:"La Chasseuse de tripes",
  quote:"",
  lead:"Elsa Granhiert, dite la « Chasseuse de tripes », est une assassin souriante qui éventre ses cibles par pur plaisir. Elle tue Subaru et Emilia dès la première boucle.",
  sections:[
    {h:"Apparence", html:"Elsa est une belle femme aux longs cheveux noirs et à la tenue sombre et affriolante, dont le calme séduisant contraste avec la violence de ses actes. Elle manie des couteaux courbes (kukri)."},
    {h:"Personnalité", html:"Sadique et sereine, Elsa tue avec une fascination esthétique pour les entrailles de ses victimes — d'où son surnom de « Chasseuse de tripes ». Elle traite le meurtre comme un art, sans haine, avec un plaisir tranquille qui la rend terrifiante."},
    {h:"Pouvoir", html:"Outre sa maîtrise mortelle des lames, Elsa possède une capacité de régénération anormale qui lui permet de survivre à des blessures théoriquement fatales, rendant chaque affrontement contre elle désespérant."},
    {h:"Rôle", html:"Première tueuse de Subaru (et d'Emilia) dès la boucle initiale, Elsa revient le hanter arc après arc, souvent aux côtés de Meili. Elle incarne la mort brutale et imprévisible qui peut frapper à tout instant dans ce monde impitoyable."},
  ],
  related:["meili","felt"],
},
{
  id:"meili", name:"Meili Portroute", kanji:"メィリィ・ポートルート", group:"autres",
  color:"#5b8eff", role:"Dresseuse de bêtes", race:"Humaine", age:"Enfant",
  aff:"Assassin → Camp Emilia", status:"Vivante", va:null,
  abilities:["Contrôle des bêtes démoniaques"],
  epi:"La jeune dresseuse de bêtes",
  quote:"",
  lead:"Meili Portroute est une enfant-assassin capable de commander les bêtes démoniaques, d'abord adversaire de Subaru avant d'être recueillie par le camp d'Emilia.",
  sections:[
    {h:"Apparence", html:"Meili est une fillette aux longs cheveux bleus, souvent coiffés en une natte volumineuse ornée d'un motif floral. Son air enfantin et innocent contraste violemment avec sa froideur de tueuse."},
    {h:"Personnalité", html:"D'une cruauté enjouée et détachée, Meili tue sans remords sur ordre — mais cette carapace dissimule une enfant seule, privée d'amour et de repères, qui n'a jamais connu que l'exploitation. Son évolution est l'une des rédemptions les plus touchantes du camp."},
    {h:"Biographie", html:"Enfant-assassin employée par une organisation criminelle, Meili est chargée, aux côtés d'Elsa, d'attaquer le manoir Roswaal (arcs 2 et 4) au moyen de bêtes démoniaques. Capturée puis épargnée, elle est finalement recueillie par le camp d'Emilia, où elle découvre peu à peu une véritable famille."},
    {h:"Pouvoirs", html:"Meili possède une Bénédiction lui permettant de percevoir, d'appeler et de commander les bêtes démoniaques sur de vastes distances. Entre de mauvaises mains, ce don en fait une arme de destruction massive ; au service du camp, une sentinelle précieuse."},
    {h:"Relations clés", html:"<strong>Elsa</strong> — sa « grande sœur » et complice d'assassinat. <strong>Petra</strong> et <strong>Beatrice</strong> — avec qui elle se lie une fois recueillie au manoir."},
  ],
  related:["elsa","petra","beatrice"],
},
{
  id:"al", name:"Al", kanji:"アル", group:"autres",
  color:"#d6a23a", role:"Chevalier de Priscilla", race:"Humain (autre monde)", age:"Adulte",
  aff:"Camp Priscilla", status:"Vivant", va:null,
  abilities:["Combat au sabre","Un secret bien gardé"],
  epi:"Le chevalier masqué de Priscilla",
  quote:"",
  lead:"Al est le chevalier masqué et désabusé au service de Priscilla, un guerrier au bras unique qui, comme Subaru, vient d'un autre monde.",
  sections:[
    {h:"Apparence", html:"Al porte en permanence un heaume de fer qui dissimule son visage, et il lui manque un bras, remplacé par la débrouille. Sa dégaine décontractée tranche avec le sérieux des chevaliers de cour."},
    {h:"Personnalité", html:"Fataliste, blagueur et lucide, Al affiche un flegme désabusé forgé par une longue expérience de ce monde. Sous ses plaisanteries perce une gravité rare, celle d'un homme qui en a beaucoup trop vu."},
    {h:"L'autre venu d'ailleurs", html:"Al partage avec Subaru le statut rarissime d'« étranger à ce monde » : arrivé de la même Terre bien des années plus tôt, il devine immédiatement la nature de Subaru. Il laisse entendre posséder, lui aussi, un pouvoir lié au temps ou à la mort — un secret jalousement gardé."},
    {h:"Rôle", html:"Chevalier et garde du corps de Priscilla, Al voit son importance grandir dans les arcs impériaux de Vollachia, où son passé et ses capacités commencent enfin à se dévoiler."},
  ],
  related:["priscilla","subaru"],
},
{
  id:"theresia", name:"Theresia van Astrea", kanji:"テレシア・ヴァン・アストレア", group:"autres",
  color:"#e0b0b8", role:"Précédente Sword Saint", race:"Humaine", age:"Décédée",
  aff:"Maison Astrea", status:"Décédée", va:null,
  abilities:["Sword Saint (jadis)"],
  epi:"La précédente Sword Saint",
  quote:"",
  lead:"Theresia van Astrea fut la Sword Saint de la génération précédente, épouse de Wilhelm et aïeule de Reinhard.",
  sections:[
    {h:"Apparence", html:"Theresia avait de longs cheveux rouges — trait transmis à son petit-fils Reinhard — et un visage doux. On la voit surtout à travers des souvenirs et des évocations."},
    {h:"La Sword Saint qui haïssait l'épée", html:"Theresia fut la Sword Saint de sa génération, dotée d'une puissance immense héritée de la lignée Astrea. Pourtant, elle détestait se battre et rêvait d'une vie simple, entourée de fleurs. C'est cet amour de la paix qui séduisit Wilhelm, lequel jura de porter l'épée à sa place."},
    {h:"Tragédie", html:"Lorsque son petit-fils Reinhard hérita malgré lui de la Bénédiction du Sword Saint, Theresia perdit sa puissance. Sans protection, elle trouva la mort face à la Baleine Blanche — un drame qui brisa Wilhelm, aigrit son fils Heinkel et fit peser sur Reinhard une culpabilité indélébile."},
    {h:"Héritage", html:"La mort de Theresia est la blessure fondatrice de la maison Astrea : elle nourrit la vengeance de Wilhelm contre la Baleine Blanche et explique le poids que Reinhard porte derrière sa perfection apparente."},
  ],
  related:["wilhelm","reinhard"],
},
];
